# Generated by Django 6.1.1 on 2026-09-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('MEMBERS_ONLY', 'Members only')], default='PUBLIC', help_text='Public jobs are visible to everyone; member-only jobs require membership access.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Candidate'), ('ADMIN_HANDLER', 'Admin Handler'), ('PARTNER', 'Partner Reviewer')], default='USER', help_text='Controls how the user appears in the admin system and how they can access jobs.', max_length=30),
        ),
    ]
