# Generated by Django 6.1.1 on 2026-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_job_visibility_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='current_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='document_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Uploaded'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_readiness',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('PENDING', 'Pending'), ('READY', 'Ready'), ('UNDER_REVIEW', 'Under review')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
