# Generated by Django 6.1.1 on 2026-10-02 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_application_admin_notes_application_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='job',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('M_PESA', 'M-Pesa'), ('CARD', 'Card / Visa'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Bank Transfer'), ('MANUAL_OFFLINE', 'Manual Offline')], default='MANUAL_OFFLINE', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='cv_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='UserAccessUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('TIER_1', 'Tier 1 - Membership'), ('TIER_2', 'Tier 2 - Verification'), ('TIER_3', 'Tier 3 - Placement')], max_length=12)),
                ('source', models.CharField(choices=[('AUTO_PAYMENT', 'Automatic after payment verification'), ('MANUAL_ADMIN', 'Manual admin approval'), ('MANUAL_OFFLINE', 'Manual offline receipt'), ('SYSTEM', 'System-generated')], default='MANUAL_ADMIN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_tier_unlocks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-granted_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'tier'), name='unique_user_tier_unlock')],
            },
        ),
    ]
