# Generated by Django 6.1.1 on 2026-10-06 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_job_image_alt_job_image_url_transaction_gateway_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('category', models.CharField(choices=[('STORY', 'Story'), ('BLOG', 'Blog')], default='BLOG', max_length=20)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('body', models.TextField()),
                ('featured_image', models.URLField(blank=True, default='', max_length=500)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('image_alt', models.CharField(blank=True, default='', max_length=160)),
                ('author_name', models.CharField(default='HBC Job Majuu', max_length=120)),
                ('read_time', models.CharField(default='4 min read', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
