# Generated by Django 6.1.1 on 2026-10-06 13:08

import django.contrib.auth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery item',
                'verbose_name_plural': 'Gallery',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client.article',),
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
            ],
            options={
                'verbose_name': 'Platform user',
                'verbose_name_plural': 'Platform users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PublicUser',
            fields=[
            ],
            options={
                'verbose_name': 'Public user',
                'verbose_name_plural': 'Public users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client.article',),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Candidate'), ('ADMIN', 'Super Admin'), ('ADMIN_SUPER', 'Super Admin'), ('ADMIN_HANDLER', 'Admin Handler'), ('PARTNER', 'Partner Reviewer'), ('CONTENT_MANAGER', 'Content Manager'), ('DIGITAL_MARKETING', 'Digital Marketing'), ('FINANCE_OFFICER', 'Finance Officer'), ('ATS_COORDINATOR', 'ATS Coordinator')], default='USER', help_text='Controls how the user appears in the admin system and how they can access jobs.', max_length=30),
        ),
    ]
