# Generated by Django 6.1.1 on 2026-10-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_galleryitem_blogpost_platformuser_publicuser_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country_flag',
            field=models.CharField(blank=True, default='', help_text='Auto-generated flag for the country, such as 🇰🇪', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='cover_image',
            field=models.URLField(blank=True, default='', help_text='Optional cover image for the job card and detail page.', max_length=500),
        ),
    ]
