# Generated by Django 6.1.1 on 2026-10-07 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_job_country_flag_job_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('short_description', models.CharField(blank=True, default='', max_length=220)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('logo_image', models.FileField(blank=True, null=True, upload_to='partners/')),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
